# Interpolation : docker compose --env-file docker-compose.production.env -f docker-compose.yml
services:
  home-config-backend:
    image: ${COMPOSE_NODE_IMAGE}
    working_dir: /usr/src/app
    command: ["sh", "-c", "${COMPOSE_APP_SHELL_COMMAND}"]
    ports:
      - "${PROD_BIND_HOST}:${PROD_HOST_PORT}:${CONTAINER_APP_PORT}"
    env_file: .env.production
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - home-config-net

  mariadb:
    image: ${COMPOSE_MARIADB_IMAGE}
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - home-config-prod-db:/var/lib/mysql
    networks:
      home-config-net:
        aliases:
          - mariadb

volumes:
  home-config-prod-db:

networks:
  home-config-net:
    name: ${COMPOSE_HOME_CONFIG_NET_NAME}
